FROM node:alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
COPY tsconfig.json ./
COPY src ./src

RUN npm install

EXPOSE 3000

CMD npx prisma db push && npm run build && npm run start